apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: warehouse-frontend
spec:
  tls:
  - hosts:
    - staging.warehouse.example.com
    secretName: warehouse-staging-tls
  rules:
  - host: staging.warehouse.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: warehouse-frontend
            port:
              number: 80