apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: warehouse-prod

bases:
  - ../../base

namePrefix: prod-
nameSuffix: ""

commonLabels:
  environment: production
  
patchesStrategicMerge:
  - deployment-blue.yaml
  - deployment-green.yaml
  - service-patch.yaml
  - hpa-patch.yaml

configMapGenerator:
  - name: web-app-config
    behavior: merge
    literals:
      - nextauth-url=https://warehouse-network.com
      - api-rate-limit="100"

secretGenerator:
  - name: web-app-secrets
    envs:
      - secrets.env

resources:
  - pdb.yaml
  - ingress.yaml

images:
  - name: ghcr.io/warehouse-network/web
    newTag: production