apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: warehouse-network

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/name: warehouse-network
  app.kubernetes.io/component: web
  app.kubernetes.io/part-of: warehouse-network

images:
- name: web-app
  newName: ghcr.io/warehouse-network/web
  newTag: latest