apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: warehouse-staging

bases:
  - ../../base

namePrefix: staging-
nameSuffix: ""

commonLabels:
  environment: staging
  
patchesStrategicMerge:
  - deployment-patch.yaml
  - hpa-patch.yaml

configMapGenerator:
  - name: web-app-config
    behavior: merge
    literals:
      - nextauth-url=https://staging.warehouse-network.com

secretGenerator:
  - name: web-app-secrets
    envs:
      - secrets.env

images:
  - name: ghcr.io/warehouse-network/web
    newTag: staging